// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/ksfile/ksfile.proto

package ksfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KSFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Routes        []*KSRoute             `protobuf:"bytes,6,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KSFile) Reset() {
	*x = KSFile{}
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KSFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KSFile) ProtoMessage() {}

func (x *KSFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KSFile.ProtoReflect.Descriptor instead.
func (*KSFile) Descriptor() ([]byte, []int) {
	return file_pkg_ksfile_ksfile_proto_rawDescGZIP(), []int{0}
}

func (x *KSFile) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KSFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KSFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KSFile) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KSFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *KSFile) GetRoutes() []*KSRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type KSRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Ksuid         string                 `protobuf:"bytes,4,opt,name=ksuid,proto3" json:"ksuid,omitempty"`
	Headers       []*KSCrumb             `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	QueryParams   []*KSCrumb             `protobuf:"bytes,6,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	BodyParams    []*KSCrumb             `protobuf:"bytes,7,rep,name=body_params,json=bodyParams,proto3" json:"body_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KSRoute) Reset() {
	*x = KSRoute{}
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KSRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KSRoute) ProtoMessage() {}

func (x *KSRoute) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KSRoute.ProtoReflect.Descriptor instead.
func (*KSRoute) Descriptor() ([]byte, []int) {
	return file_pkg_ksfile_ksfile_proto_rawDescGZIP(), []int{1}
}

func (x *KSRoute) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *KSRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KSRoute) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *KSRoute) GetKsuid() string {
	if x != nil {
		return x.Ksuid
	}
	return ""
}

func (x *KSRoute) GetHeaders() []*KSCrumb {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *KSRoute) GetQueryParams() []*KSCrumb {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

func (x *KSRoute) GetBodyParams() []*KSCrumb {
	if x != nil {
		return x.BodyParams
	}
	return nil
}

type KSCrumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Example       string                 `protobuf:"bytes,4,opt,name=example,proto3" json:"example,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KSCrumb) Reset() {
	*x = KSCrumb{}
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KSCrumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KSCrumb) ProtoMessage() {}

func (x *KSCrumb) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ksfile_ksfile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KSCrumb.ProtoReflect.Descriptor instead.
func (*KSCrumb) Descriptor() ([]byte, []int) {
	return file_pkg_ksfile_ksfile_proto_rawDescGZIP(), []int{2}
}

func (x *KSCrumb) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KSCrumb) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *KSCrumb) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *KSCrumb) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

var File_pkg_ksfile_ksfile_proto protoreflect.FileDescriptor

const file_pkg_ksfile_ksfile_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/ksfile/ksfile.proto\x12\x06ksfile\"\xb8\x01\n" +
	"\x06KSFile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12'\n" +
	"\x06routes\x18\x06 \x03(\v2\x0f.ksfile.KSRouteR\x06routes\"\xff\x01\n" +
	"\aKSRoute\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05ksuid\x18\x04 \x01(\tR\x05ksuid\x12)\n" +
	"\aheaders\x18\x05 \x03(\v2\x0f.ksfile.KSCrumbR\aheaders\x122\n" +
	"\fquery_params\x18\x06 \x03(\v2\x0f.ksfile.KSCrumbR\vqueryParams\x120\n" +
	"\vbody_params\x18\a \x03(\v2\x0f.ksfile.KSCrumbR\n" +
	"bodyParams\"e\n" +
	"\aKSCrumb\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x18\n" +
	"\aexample\x18\x04 \x01(\tR\aexampleB,Z*github.com/RowanDark/kitestring/pkg/ksfileb\x06proto3"

var (
	file_pkg_ksfile_ksfile_proto_rawDescOnce sync.Once
	file_pkg_ksfile_ksfile_proto_rawDescData []byte
)

func file_pkg_ksfile_ksfile_proto_rawDescGZIP() []byte {
	file_pkg_ksfile_ksfile_proto_rawDescOnce.Do(func() {
		file_pkg_ksfile_ksfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_ksfile_ksfile_proto_rawDesc), len(file_pkg_ksfile_ksfile_proto_rawDesc)))
	})
	return file_pkg_ksfile_ksfile_proto_rawDescData
}

var file_pkg_ksfile_ksfile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_ksfile_ksfile_proto_goTypes = []any{
	(*KSFile)(nil),  // 0: ksfile.KSFile
	(*KSRoute)(nil), // 1: ksfile.KSRoute
	(*KSCrumb)(nil), // 2: ksfile.KSCrumb
}
var file_pkg_ksfile_ksfile_proto_depIdxs = []int32{
	1, // 0: ksfile.KSFile.routes:type_name -> ksfile.KSRoute
	2, // 1: ksfile.KSRoute.headers:type_name -> ksfile.KSCrumb
	2, // 2: ksfile.KSRoute.query_params:type_name -> ksfile.KSCrumb
	2, // 3: ksfile.KSRoute.body_params:type_name -> ksfile.KSCrumb
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_ksfile_ksfile_proto_init() }
func file_pkg_ksfile_ksfile_proto_init() {
	if File_pkg_ksfile_ksfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_ksfile_ksfile_proto_rawDesc), len(file_pkg_ksfile_ksfile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ksfile_ksfile_proto_goTypes,
		DependencyIndexes: file_pkg_ksfile_ksfile_proto_depIdxs,
		MessageInfos:      file_pkg_ksfile_ksfile_proto_msgTypes,
	}.Build()
	File_pkg_ksfile_ksfile_proto = out.File
	file_pkg_ksfile_ksfile_proto_goTypes = nil
	file_pkg_ksfile_ksfile_proto_depIdxs = nil
}
